global:
  scrape_interval: 60s

scrape_configs:
  - job_name: node
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: blackbox_http_2xx
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://npm.jerome.cloudns.asia
          - https://portainer.jerome.cloudns.asia/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox_http_2xx_or_404
    metrics_path: /probe
    params:
      module: [http_2xx_or_404]
    static_configs:
      - targets:
          - https://panel.3x.jerome.cloudns.asia
          - https://sub.3x.jerome.cloudns.asia/sub/
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: blackbox_tcp
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
          - jerome.cloudns.asia:39876
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
