# vps_oracle/k3s/apps/hello/k8s/backend-canary-destinationrule.yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: hello-backend-canary
  namespace: pr-lanes
spec:
  host: hello-backend-canary.pr-lanes.svc.cluster.local
  trafficPolicy:
    outlierDetection:
      consecutive5xxErrors: 3
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 100
