apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-backend
  namespace: pr-lanes
  labels:
    app: hello-backend
    lane: baseline
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: hello-backend
      lane: baseline
  template:
    metadata:
      labels:
        app: hello-backend
        lane: baseline
    spec:
      serviceAccountName: hello-backend-sa
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: hello-backend
          image: ghcr.io/jeromefromcn/hello-backend@sha256:2099b54b518ce8d9f7b7c5e3e4344e564125f43b69e630d7db9dccf9855a92de
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
