apiVersion: 1

policies:
  - orgId: 1
    receiver: Telegram-Critical
    group_by: ['alertname']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      - receiver: Telegram-Warning
        object_matchers:
          - ['severity', '=', 'warning']
        continue: false
      - receiver: Telegram-Critical
        object_matchers:
          - ['severity', '=', 'critical']
        continue: false
