#!/usr/bin/env python3
"""Turn docs/demo/ into a site build directory without touching the source.

Writes <out>/docs/ -- a copy of every page -- and <out>/mkdocs.yml, the
hand-written base plus a nav in README's demo order. Standard library only.
Nothing here is MkDocs-specific except the nav format, so moving to another
generator (Zensical) changes only that.
"""
import argparse
import json
import re
import shutil
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent

# | 07 | [GitOps self-heal and rollback](07-gitops-selfheal-rollback.md) | why |
ORDER_ROW = re.compile(r"^\|\s*(\d{2})\s*\|\s*\[([^\]]+)\]\(((\d{2})-[a-z0-9-]+\.md)\)\s*\|")
PAGE_NAME = re.compile(r"^(\d{2})-([a-z0-9-]+)\.md$")


class PrepareError(Exception):
    pass


def parse_order(readme: str) -> list[tuple[str, str, str]]:
    rows, seen = [], set()
    for line in readme.splitlines():
        m = ORDER_ROW.match(line)
        if not m:
            continue
        num, title, filename, file_num = m.groups()
        if num != file_num:
            raise PrepareError(f"README Order row {num} links {filename}: the numbers disagree")
        if filename in seen:
            raise PrepareError(f"README Order table lists {filename} twice")
        seen.add(filename)
        rows.append((num, title, filename))
    if not rows:
        raise PrepareError("README.md has no Order table rows")
    return rows


def prepare(src: Path, out: Path, base: Path) -> list[str]:
    order = parse_order((src / "README.md").read_text())
    base_text = base.read_text()
    errors = []
    for key in ("nav", "docs_dir"):
        if re.search(rf"^{key}\s*:", base_text, re.M):
            errors.append(f"{base.name} must not set {key}: prepare.py generates it")

    # Every markdown file is checked, not only NN-*.md: the copy below
    # publishes all of them, so a stray or misnamed page would otherwise go
    # live with no nav entry.
    pages = set()
    for path in sorted(src.glob("*.md")):
        if path.name == "README.md":
            continue
        if not PAGE_NAME.match(path.name):
            errors.append(f"{path.name}: page names must be NN-lowercase-slug.md")
            continue
        pages.add(path.name)

    listed = [f for _, _, f in order]
    errors += [f"README Order table links {f}, which does not exist" for f in listed if f not in pages]
    errors += [f"{f} is not in README's Order table" for f in sorted(pages) if f not in listed]

    if errors:
        raise PrepareError("\n".join(errors))

    docs = out / "docs"
    if docs.exists():
        shutil.rmtree(docs)
    shutil.copytree(src, docs)

    nav = "".join(
        f"  - {json.dumps(f'{num} — {title}', ensure_ascii=False)}: {filename}\n"
        for num, title, filename in order
    )
    (out / "mkdocs.yml").write_text(
        base_text.rstrip("\n")
        + "\n\n# Generated by prepare.py from README's Order table -- do not edit.\n"
        + "docs_dir: docs\nnav:\n  - Overview: README.md\n"
        + nav
    )
    return listed


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--src", type=Path, default=HERE.parent / "docs" / "demo")
    ap.add_argument("--out", type=Path, default=HERE / "build")
    ap.add_argument("--base", type=Path, default=HERE / "mkdocs.base.yml")
    args = ap.parse_args()
    try:
        nav = prepare(args.src, args.out, args.base)
    except PrepareError as e:
        print(f"prepare.py: {e}", file=sys.stderr)
        return 1
    print(f"prepare.py: {len(nav)} pages -> {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
