apiVersion: v1
kind: Namespace
metadata:
  name: mesh-observability
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mesh-observability-quota
  namespace: mesh-observability
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: 320Mi
    limits.cpu: "500m"
    limits.memory: 640Mi
