- Infra Services:
    - Nginx Proxy Manager:
        icon: nginx-proxy-manager.png
        href: https://npm.jerome.cloudns.asia
        description: Reverse proxy / SSL management
        container: npm
        server: my-docker

    - Portainer:
        icon: portainer.png
        href: https://portainer.jerome.cloudns.asia
        description: Docker management
        container: portainer
        server: my-docker

    - Grafana:
        icon: grafana.png
        href: https://grafana.jerome.cloudns.asia/d/rYdddlPWk/node-exporter-full?orgId=1&from=now-24h&to=now&timezone=browser&var-job=node&var-nodename=node-exporter&var-node=node-exporter:9100&refresh=1m
        description: Monitoring dashboard
        container: grafana
        server: my-docker

- Apps:
    - Trilium:
        icon: trilium.png
        href: https://trilium.jerome.cloudns.asia
        description: Notes
        container: trilium
        server: my-docker

    - Vikunja:
        icon: vikunja.png
        href: https://vikunja.jerome.cloudns.asia
        description: Task management
        container: vikunja
        server: my-docker

    - Apprise:
        icon: apprise.png
        href: https://apprise.jerome.cloudns.asia
        description: Notification forwarding
        container: apprise
        server: my-docker

    - Open WebUI:
        icon: open-webui.png
        href: https://ollama.jerome.cloudns.asia
        description: LLM chat (llama.cpp)
        container: open-webui
        server: my-docker

    - SillyTavern:
        icon: sillytavern.png
        href: https://sillytavern.jerome.cloudns.asia
        description: Roleplay / character chat frontend (llama.cpp)
        container: sillytavern
        server: my-docker
