---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: open-webui
  namespace: llm
spec:
  encryptedData:
    WEBUI_SECRET_KEY: AgCUBgtjZT2XPvHi8YB5x9aGXtzXMBakah1Hvk7FA7AdReOo9ll1I05RHDIvx/psp4AC/FqlU/8oKpjigiWtw+oVE00pFvuO31BCSSW7+U1vHLjgdktxoWr8fMNkWOyLi7sMk1EFsn5m4TwN4baFrhRU9pvvjHaPO1abT0lXhAMZg8T8gzTM2CLZ9JfIwQR76XuNhtN4zD9rhmj5qsXpRHnJF9LQUx2jh5WjnPQFBdEK/ZEcR3g58GnLNwWY69BKq+x+ENSxAKq8X8OlAuL1dBTzA5krvWTn7pqJI8NNTa5Oa+sdyK5kYDu8hJjh7KlgPOlLsTKQfPTWUeCiW4vc8vmhZLx52jzmnlk6b6XNCpqAUufH02Tiauk1oG2HoI0kaG7ApOeGsAhE8l2gwNZrHc/JNBXdu5DReJprd8gd9fZcY4h19f5Qby0X4fxDcFF4PZ0CLjHOVY37kTbg0r3lsdg5avxl5xtfrQpw/yxsw4wSwNh2cKYx3aFTIvyCm/MJcD92wluBakYZfBOkc0tEUMOpQF9ItR+1OQBeRVCNTO6L392Xg09BGw837ai1Zp1HUZCYiIiR+sW+oMrQrIPE1jWegzhyc6IRZ2xVIFBGNbEj1LIbFGGs5nJc5MgZgdXfzfd3SgwEv/S2uzssFfbR+gLWbWUaoVuybK7kqqoTcq8WfKvwgof/174z6EmRM7YEM9pLDyqw0odbb4SjnqS77BIbR3BbihiggqNsPBFNyqYA/5NFqT9sbgCwSL8zewGLTA+Wnh2rqyzLM5I3QCJJRqH8
  template:
    metadata:
      name: open-webui
      namespace: llm
    type: Opaque
