---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sillytavern
  namespace: llm
spec:
  encryptedData:
    SILLYTAVERN_BASICAUTHUSER_PASSWORD: AgAZI6mocXhUhxXgeaC/RZJUSfThXTFsOkvAriIUp6LCuk/JXung0ts5T7BCXKJi6ZNHr2g5snfUTvdvbcHwNxET+ZYqdulfqbV627re4oLFkQYdBdW8eovaiAZXRKuQynQzMZjuU/2Ap3/zAy3rKcQ5EdONhPSLD2qGRn9PV15Tt+afnH/fT6yTvl+5eUxz7w4Ha56iCEe2Lt9t8WVgxJZlwm4NjRHnDIEIr3SaP4X1O5IfhAZs06CFt8yLFV/R/KSRQOyVQ4Nr8Mill7AmxLiuBjfYKkXKwDWQ0h8oPegWF0uY8PivvcX2HqHlnx/M+KBecSRuAQS/nVEqiUnFQzMeWY3T01Da+wo39lSV/InAxcMpwC35NP2qAhWpL3PjL6JY31CQf6QIL9hA6BCWfUHBpwmfF8ZvrJPmSM78MVv8EFCmZmioFhN9xPMqKZ6H0duobMqKLV9BWze9it9wIBVBTZYOE+REhDQOiVduB1ZP+bEQKXk6U+IysfdE0Ri3cta5Zpgy1KiSiydjOqToUxxePxNzH8B1h3hGHmgddmH3PzrTu5hTGuXftKyiutFKPpQ5OK5/twHo1KhM8s0ykHpYLXUjP/37m5dFSwXzPwTth8f0JaCWeL9kxcw8bMMA3SG2MGNB3J6QyyLoHHdjEWAlRFc8xpVfceLZfBHKnIHoK5Xkbtcc9bsZFAP+iywnKSZ51PPxodv3jcnH/KA2
    SILLYTAVERN_BASICAUTHUSER_USERNAME: AgB0pw3UJdWCsl5UPxvw5/KiVIqfgnLP+9Xo09zD8/SwxSne4GKKylX9W59SNI+nhKDwbozHT1x6kFzI/bmuuHW/aCN15RLMLmh2+OmjWsOU2IFySyph8hJMpUqJG7Xw2UGHm8Qv4sml2Nj2RTyMxJ+grXSct+cZ8/qawK+EKHliFqkiNwDTVe/CC2WdLTwiBsMdR7Ckb1cMko0YMDeowNhZ0OLRdVqD3pwMrDDOPvzbJnUljKKIHLvYFKxeQeRAEXnDs/3bER4sWl8xgBwl+G5VB2+gb35+5wUEA7QuNX2kWoiTtfoSLZ2CGHHiIkftq9W/J17dnpR3e9LzUyJi0CXxHm2t3qc9+iuS6tur2CFa7MmSO1d0ad2NoddIvvQVz7AKBcfqf3MQLWgZdwEjiByzzceyZWYzCslZBD3StXnFoWkgLCeRQgNZLnJpVlK9ePJku/8JL0fCDkbDKejq1GIYzpzGUsK6CJLaCnaUkdvViBz5e+bKsuXx27O5ySCjHB9z8tt4jpcMePYM2L88sZeIVFrI3cHGxl0PQznoVej6lQWUh97gyihqe+HOQ47LMJDYfutK+X/XVeUEy+8hC7rqRYZmZ3TtL/z4EE3DNOvd+AT9SO6X4qOtrVRHHh1Ltu1wM6UMyQ8u1jeD0+oTsipN3nUuPenSCogKzHDHS9TK+PHoo1F5miCjkRkKxidANDNyv0xcl08=
  template:
    metadata:
      name: sillytavern
      namespace: llm
    type: Opaque
