---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vikunja
  namespace: workloads
spec:
  encryptedData:
    VIKUNJA_SERVICE_SECRET: AgALQTld10AiB34VwFA8IMHm5MsDf/t5mWHCMCyYGb2ud8hL6pOJ7Ges6UVmoxn7dQU1kqjJpuMcMmKY4w1k513mEpgzNbwGggSK4t8suGOrJ3CcyXdUjM4c251PAWA6IQwUdRFwnzrap7hkNXjAJqcxIUar5NOPCFTbWu+eCFLH4EtmtlAeIRarCLejYHRpS0BkvJ1JsdsyPFb8Xl0ZVggctlNZdcII8ZcusBJskW1fMJK40hYvPaBprg7ScgakQA5qp5A4hCOBoywptiEOCMkV927Krir8STzVkAkG8Mni0qy+fI0S9rAOAzg9jLlsh8hNSrz4xWhxolne0JlGVIrlpIEQBEGSaHqjoVjgS0v0d4JQ/H+Amg1eYkxF7qh8s6NVFzYCk3D2nCj9WG9ssR3Plvi8GR8c9qksZH8vUHPlhpFA7Hfig1/2CTbkCOT1oSVtNnVW6OKxWgmep9rpqrnHjcSea7Y0RykYIIBIe/8h4ijNLIr+0wAgPLEQxEzycOO5NVjdqJZzoH4s1BYjAf1tdhS64TZvJWfMST78/qfQuAVMbxWTjpLo+7XCqJnS5xI0yYTvWUFxtpApUGSbapAf21dp0tpoTR/lqdr8hHA62CNfLm7FXIKaHqMqFqO8WzzvCnNkrGl8rD6Q77IB3jEhLv/VDBFFivGWE6QLGk5TyzGgxNyRcPDi83B9MGWL9R+CvkAFSPD4s6Y2Cudi/LLfG3meSMN9tej2ayrC/nrSIb5zpihUnDZEPlpdIm5Btdi3IZpcYF1WyAu+qmAnZ/dc
  template:
    metadata:
      name: vikunja
      namespace: workloads
    type: Opaque
