apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vikunja
  namespace: workloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
