title: Jerome's Homelab
theme: dark
color: sky
headerStyle: clean
cardBlur: sm
hideVersion: true

quicklaunch:
  provider: duckduckgo
  searchDescriptions: true
  showSearchSuggestions: true
  hideInternetSearch: false

layout:
  Infra Services:
    style: row
    columns: 3
  Apps:
    style: row
    columns: 3
  Lab:
    style: row
    columns: 3
