apiVersion: 1

templates:
  - orgId: 1
    name: server_alert
    template: |
      {{ define "server_alert" }}
      {{ if eq .Status "firing" }}
      {{ if eq .CommonLabels.severity "critical" }}🚨🔴 CRITICAL{{ else }}⚠️🟠 WARNING{{ end }}
      {{ else }}
      ✅🟢 RESOLVED
      {{ end }}
      {{ range .Alerts }}
      {{ .Annotations.summary }}
      <a href="{{ .GeneratorURL }}">Source</a>{{ if .SilenceURL }} · <a href="{{ .SilenceURL }}">Silence</a>{{ end }}
      {{ end }}
      {{ end }}
