apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-postgres
  namespace: dify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-postgres
  namespace: dify
  labels:
    app: db-postgres
spec:
  replicas: 1
  serviceName: db-postgres
  selector:
    matchLabels:
      app: db-postgres
  template:
    metadata:
      labels:
        app: db-postgres
    spec:
      enableServiceLinks: false
      containers:
        - name: db-postgres
          image: postgres:15-alpine@sha256:3d0f7584ed7d04e27fa050d6683a74746608faf21f202be78460d679cc56461f
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: dify
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          args:
            - postgres
            - -c
            - max_connections=100
            - -c
            - shared_buffers=128MB
            - -c
            - work_mem=4MB
            - -c
            - maintenance_work_mem=64MB
            - -c
            - effective_cache_size=1024MB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "dify"]
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          resources:
            requests:
              cpu: 250m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db-postgres
---
apiVersion: v1
kind: Service
metadata:
  name: db-postgres
  namespace: dify
spec:
  selector:
    app: db-postgres
  ports:
    - port: 5432
      targetPort: 5432
