apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - networkpolicy.yaml
  - db-postgres.yaml
  - pgvector.yaml
  - redis.yaml
  - ssrf-proxy.yaml
  - plugin-daemon.yaml
  - storage-pvc.yaml
  - api.yaml
  - worker.yaml
  - worker-beat.yaml
  - web.yaml

configMapGenerator:
  - name: ssrf-proxy-config
    namespace: dify
    files:
      - squid.conf.template=config/squid.conf.template
      - docker-entrypoint.sh=config/docker-entrypoint.sh
