apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgvector
  namespace: dify
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pgvector
  namespace: dify
  labels:
    app: pgvector
spec:
  replicas: 1
  serviceName: pgvector
  selector:
    matchLabels:
      app: pgvector
  template:
    metadata:
      labels:
        app: pgvector
    spec:
      enableServiceLinks: false
      containers:
        - name: pgvector
          image: pgvector/pgvector:pg16@sha256:a36250871de0833b8757561c72f2477ef1ddd1101afa4e617fb552e0de514c6b
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
            - name: PGUSER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dify-secrets
                  key: PGVECTOR_PASSWORD
            - name: POSTGRES_DB
              value: dify
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready"]
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 30
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pgvector
---
apiVersion: v1
kind: Service
metadata:
  name: pgvector
  namespace: dify
spec:
  selector:
    app: pgvector
  ports:
    - port: 5432
      targetPort: 5432
