---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-pr-generator-token
  namespace: argocd
spec:
  encryptedData:
    token: AgC7Hu2/ebw6oGmPPT8bzZfIY0gNaahadkuYFAxufEg6fN35sTugN/Fg5NGP0xvNtCznnKNbpWlAd4qpij8N7YGa2aTw9UbU/9Yes7/NsQHl2NB4T8UlwrG180O93BRrYYqa9R4X3wjSVQNrDgF/00LiPa1I3fSsXOhngH3VL+42KVGeSlQ0LCA+zD9b8ouzIQ8C+Gwg+SaABwbRonCcM29NFDM51gX/LYCLQ13Nj/ZTSHsKa8hebH4mAyGUrS3qZthPlVnN6Jj9Zd0teNLrZ0owQsaGsVJjm64c4H07RmJw3eHDmX1ga2/xhzbagFXTJ1I0tSld/VX6ywf/fL97r6T70z9sy28T+044SRlZjRCk/YRZqYJK9cAn4SCZjNBgeSpjVkx15W+oIQiZWXBtadCcVQsDcX/PNUtMZpCl4HGa1f8uHgA+0w8DkrN6eBj9mToubP93QhpPEvbqRH8A1ruUZnZISWivsaOkAj5PnXNHYyqr18arFxP20pP8JtkO61nOp+6cc4Aiw+VcXAN6Q9YGj8rSPqFXHBaMsj0ZPw1Ft8KAg1k0EFb1BWodLXbXtiR7WQSjy9DUr8D0ginVMEAgqWMPoIV5QTada86X8VxbgPPcg+cfcPhY1Ed2R7cIW2NlLgt1hGlN0ss2IwCWxNaOzV7oa8FK+6dcQc1oussftnYzoq2ud/qZ1e7jgMqDlmro14GHOGp0brSNVJLJizaLbFbRhU9Z+wSO2Z+6AKuOa6UAJLB0QcHoVDWjPPRz1Cf0Kp0q6jSMWGDrvW3T4kdz6IFPbBQozuWlUoVe2XjcLcYcaxk2qZHQIz21Eec=
  template:
    metadata:
      name: github-pr-generator-token
      namespace: argocd
