---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lab-db-credentials
  namespace: lab-environment
spec:
  encryptedData:
    password: AgBKmyHAzPAJ3Dal4X5SXIH4y5564grIi2YQavh3OnmbVT+NiRBNI8jtWdClJX1K4+3mfVsGIiRhCitln7wzuswOQXl4sqDVTetHM6KDwW/C8KKx8iPiO1gTw5/ivVdOZjB17QRgojrPINLhhWUbU4eixB+byN3C5UxtL6bHm59fa/4s2t95O577PLoX5QgPg7S+np4pauV+8O9nX1aXT8lfXCr6ZWxKqHk7+HOvkQ30i/aEIyVN5WrQOgJ2lIHOwCUJkUgdV/RjRbY2dnNxobZsyBH+5Pdy5PlCp6nP5jxRQeikY7aZSbCQ1lMTzraDMgI7BvPRZ5MKYsHkhCezuGPVdWnIpvAqplDFtx3j2ENXcQ7vFmjo6Z/WcQkJ2zwVbpipvaLZZK9jkrdP1CW5Jc60ImrT2mG+sUpAy9oVdRGaT7J7IllW4mGv0cy/0Y/oEvc3LJcEj/BiWJpw2YqsJH/gypvBobqa18dPz0iH6OXAATf/Ph7WFKjUoVEtygUsrZQephgmrjWJyV5+fM5MKZuQ+jlymUCg9lSFixLi09vVo3UNHc9Uy3VQObou9zhBXTn0ZVFep/biES0qYGkAXM/8OsNuYCpIgTTLHyjWNtL53OvXhXAphCYMg0XO8gjkQgtOMrivNC8WNKdHJ2kprGCKqVQSgC+oHYTsmx58CS1po4cNNzyWGGdbcB5HllljtZsyVPkBnUI6Cgb2BM6/eEXuP/LJ69uB0TLtGQWxhQ+ugg==
    username: AgBU1wLg41ov+L3yj8EgWD2uVp0qst5SJTpNQQOI/+UV7GoIkv7FdeaTphYAJo1EKE7dOYo8FxwpiJwmRdcH2Smki6FlGbSpXB3lethvWoYj6M9wB1JrJ4gv8a8h2B1L3G+PuDFJnr8+uUNMw6F92PCfWi5P/c3tOJBug+DW3mUqwJELYXFKo9roXAvbD5kjJuyXnB2F/Z0aK1cL3TJsPSkAHwWg5aszqP48SZBTIgTupwqcaOJUfBl7DWFQ/8Y8AakXZdFIOlz58t0Rt+oJZ2c/cr2zZdDWh+AwQ/R4eqB2J4wUuhWOJ5JATishKCYvse1/m8lsmUdnKzQSE1HEe84In6zyrzbE9gbMY6ZMFAbT+YcT1a5LoOIWPbE0ma7+7lzbyeo+wOs/UJ/nyyk8yXhs8PQmUjF0nZrI8vzxtyxyEbPcy77bJLFu0OUDG9sf5nf5YLJXYXYJYhlr0gyGlTuJaAE5hMavDq/RZ3cSKqx/sjesSd08pIbo4IAzak1PKE8I1Wpl0MRXxFG2TDYUEiogbB6eBVWRPtRaVhzbX5rgHcDOfMgEZP8VtvEoJfp7FGycQ5TBBYD0ahzlx7shigmW6TG+13GIaCpmSyNGOXVsQTdpu4l983Z75JFY8spmjca4KHeo3o1rqGmI5k5voufqfLJviRrcV24WHIxgG3y3oBGiC7axedRVVK+0ErWMAPSdjAo6UrqVQp0=
  template:
    metadata:
      name: lab-db-credentials
      namespace: lab-environment
