---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lab-db-credentials
  namespace: lab-environment
spec:
  encryptedData:
    password: AgAAM35aOHQpecVIA3SbgskhmriBfhLGuhsB03I9b45ehuPOnK/HE76hcIihemxcDecm2R2G63mc91JO4kd0VaOiVuXK24yyO9r4PAdrMq3omhs9zhNsi2P1zAGCuRYsnMxibAVR++YfviMAqKXHN3kUsy43b8AXIdu4dO3IpeUnKOIhIFPzmzLMdkYRXxUo8OXyxiDv1uX+yCFmzLf7vJ3GgZIZtMqKBg8T/kcEcaqnPg4czQxyhomcmRltkqpWuuYrazXYNh1qhPcJqmkHfItSm7RYyAOlE1+kdFUOo+QSlTTQn5+lFCXe3iEc8cDXv0PxW4v8Gz4jvpS+V4LC1ilRwxKg/gD3grz/RloRt71fS2YuRiQE6zB9yMMRmRiAA9xUl1QCf8qm4DznClre483LbTLf9xy0Nbb6g/mSkl+S6C/iGjF3FaN5Uex/mB5ebyhjm21JpiV6q6WlySv+SespRKz9mR52ijfPt5qXLBdegyIdmcuTSUiz0OR9gl9XWMKN0irQ4GBK1t6OvSQGDlWLYU4FQems8MGwfL6dXv09MiedtLSZNzuzW6QQmD6P7UP0zNf5Ekjlowp+pE+VV/tK90TyibPrTb3lOEbeakRIETZse/MGKzIbvWEfZJ/RJFChIzDkXo5D6z8fBD9gH9KnKnwym5sH54ZB4EsM2uswHtlFub+oF8GkTGeZsdOugvhjUIYm+9vHcba7pyCuXPRlOJf6fEYz39m+kdyK3m70TA==
    username: AgAYbpriYlXy3DZnShKmsh17Njj5LU6ZhnAT2xGV+OGWkLuCHA9eqXu4zQ136gq6JByESeCxIe/u1sjPHUjcpg9cjYcyZA2ZPg1e8YJvqXSwDBtMZDOqFs6zskZOcgYQSaaA1b8FEV3H4ZenYgmFdE//UBLIFh5RmI/BGjhcWFQf8+nwNJxKAkL0Q2c+wm7MsYrCPMmEB0hqqVT16tn5ZqAUJ+d1KhaKxAfxiLpUFqZ1hWfW2koCn0bw0dKEQwxHa0BxiNPe+w0jx4e3sv0dLvvyCFr6Y9Jmg1F/rvWJCjGmuwhvMwqj13ouMkbHY/lGiXvy24GagIDLpoXi1sb9RxdOn3bN6xXP36naP82cH1Lznf6hoJDldaeCr9aIVmZf3ODo/57Skk19LfHCBg5GcHYlBM3ENidTlxlejqXV5CgmsjwBpPkoEQqkj5xtOGiGwaXfrh2fT0WCYJEcJfxEzHXDBMey7hQuXUTQXkKqvY4Ik20G4iewV0pYjlAp4Lm2Gun0VeKafRKB5zr6BdmGPmeLLx6IlzGF+ayL+UfrC8UiaoJ/S2mQy5lMvYGk0GLujkiMg/q0Mt8ImKrdT5TPHbi+H54lreyAXfBlgIvds+DylLOUR/Uy6nok8cQ9w5Owo+jvcTMo41kdjMBtjzuagCfUvQ7C7wfNVYdjqWeTTOvrRanZc9pNyptFqPS+VnZUKK1ZyiSSwljezgg=
  template:
    metadata:
      name: lab-db-credentials
      namespace: lab-environment
