---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: lab-db-credentials
  namespace: lab-environment
spec:
  encryptedData:
    password: AgAEzqenwUO4GtK1bsphM3U+PmjtRKzBZHDMlNXrq6/Myw/0rNu0wdMNiYAQCSLSla1xoig3bga5daymKPm/fS+zv0BBJGrbC30VtoOyrhKKUo+0S+CmHB7dSn8QzfmPomNLDwsEmQ4rdSQ2c10LrNA1bOVpBRzfNTyTqU80cjDRV5M7SewILVMJW2HCfwS2SrZ1CzEA7klK2xbXTGujPmN/CQmG85csIj5DHopHPKh0iL2EGx/0a4oR+RSdZKlM9gJbi3nW4EjgnH9kmMulYcrzScuhUWjapP0MbdhjsV+7KdnneH/2YIl5QxcXO4kvSt42BY6hz45r0mcGVxO98smUqENptiq/+5aWor12WfMiCgJ1LLEYH6RoNxPOippzkdvl2zrDDsZzBSjugx1iEA8zYSlOXJ+Qr7vXZpNHWLANyGB95iMA8nemhZMR1UmwJjR9tUQy9yTUYJZ5tyt2Gh3ss3EjJ7cqr9gLOG90f0nhWbYOMMtiwzFkNA/YlOf0jI2Mzg2oPYmbU+nIiYIFvLDJmF855NRdcTRHW9NJWCg+VpMqg+ouAFT4n6UN/rF7PTaKyD42jWCumXAAxvMqIcVNGAPLXH559j4uDmwCrlLgfBhjsha5KuqV7eq5LG1HgNe1N9CGZmTJFID446Znmju9k9oB08PL2XAgWSdHiZqSdSXbAKi01tRIy02sAxCyJktBGmx9gS+t7pebzBOtiTUxCy64lyqa1WmiDia05q1b
    username: AgBRtXydqsIib+7T6S1c3Vv8plBWCgD8dy6toCYM3jNGEnwvhzpqCdiyuQZWHUEPoh/WqYhkSx5WA6kRag/b3NG1X0Ug3yfBghGg7WzRhK6d4hYoP6X4VgoPZ0wDBENrcAQv3JQrmsgiSi7WxyM+aFeV4UWWiWf1AsWaiMEbl2fJvmrxcLMantqenAxSscNO7+dI1hCr2ETMRzdIbWEkKqy74TDjMEv1vplAM7TsCDuktWc0ot7gVR7TZ/zkivWCuhtznmKIz4YEtLsyH+W94z2dYXX2hcwx3t2UejxoBfycyXgVpcYx/u+0h/rE5Q8eYcjGC5wmNmYQfuyDVspVrrrlxuhPE+vR4JL6b1FsGh3j+pSiFBmf+uBA2p0ViARkQcuBLnqpGA/edRSYcCVigMVFnxp0UA6CmFVt3+D6MkPl/5NlZd3YrnT1V2H+0SV0FoRwuM9I9ymBqio/Hv9nFe4If3HX0yD7nLJdri5nV5+0T423AxHwfif0lSomFGlym+SRq7ur2+fDBztrJrpBhFUUNIE2kA5RO4wPoR0S+T9l+PHxKqnQD8TEfpO8EbdmXqned4fwcZFcqiygFXvfE1+hxJJ9/ALe7Cko8A/eO9rYVKvZCL70pIZleFIcjfSs03yrsFZoDM2vzx4n9WaX07OjtRit2+5Ngr5AGwJD4lxz7L0bufqF7boGGV40mb8VS3+wu3DoqrSy9XQ=
  template:
    metadata:
      name: lab-db-credentials
      namespace: lab-environment
