apiVersion: v1
kind: Namespace
metadata:
  name: llm
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: llm-quota
  namespace: llm
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 4Gi
    limits.cpu: "5"
    limits.memory: 13Gi
