apiVersion: v1
kind: ResourceQuota
metadata:
  name: pr-lanes-quota
  namespace: pr-lanes
spec:
  hard:
    requests.cpu: "400m"
    requests.memory: 768Mi
    limits.cpu: "1200m"
    limits.memory: 1536Mi
