apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-hello
  namespace: workloads
  labels:
    app: placeholder-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placeholder-hello
  template:
    metadata:
      labels:
        app: placeholder-hello
    spec:
      containers:
        - name: placeholder-hello
          image: ghcr.io/jeromefromcn/placeholder-hello:0d3e52314b0950b893e32f684b5011ce8abdc798
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
