apiVersion: apps/v1
kind: Deployment
metadata:
  name: placeholder-hello
  namespace: workloads
  labels:
    app: placeholder-hello
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: placeholder-hello
  template:
    metadata:
      labels:
        app: placeholder-hello
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: placeholder-hello
          image: ghcr.io/jeromefromcn/placeholder-hello@sha256:3b8929d1913203f822539731236bf1127c178729588647703eed7ea15e831992
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
