apiVersion: apps/v1
kind: Deployment
metadata:
  name: apprise
  namespace: workloads
  labels:
    app: apprise
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apprise
  template:
    metadata:
      labels:
        app: apprise
    spec:
      enableServiceLinks: false
      containers:
        - name: apprise
          image: caronc/apprise:v1.5.1
          ports:
            - containerPort: 8000
          env:
            - name: TZ
              value: "Asia/Hong_Kong"
            - name: APPRISE_STATEFUL_MODE
              value: "simple"
            - name: APPRISE_WORKER_COUNT
              value: "1"
            - name: APPRISE_ADMIN
              value: "y"
          volumeMounts:
            - name: config
              mountPath: /config
          resources:
            requests:
              cpu: 25m
              memory: 192Mi
            limits:
              cpu: 300m
              memory: 384Mi
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: apprise
