apiVersion: v1
kind: Service
metadata:
  name: apprise
  namespace: workloads
spec:
  type: NodePort
  selector:
    app: apprise
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30085
